### ISSUE TITLE
Thank you very much

### ISSUE THREAD

**Issue by qy201901** [LRAbbade/PBFT#7]
Dear Lucas,
     I meet this problem, could you help me solve it:
    [2020-04-30 14:17:43.285]: Listening on port 3002...
[2020-04-30 14:18:58.375]: Response received, adding network nodes
[2020-04-30 14:18:58.376]: undefined
undefined:1
undefined
^
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/Users/qy/Desktop/PBFT-master/networkNode.js:469:21)
    at self.callback (/Users/qy/Desktop/PBFT-master/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.onRequestError (/Users/qy/Desktop/PBFT-master/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Best wishes,
Yi

**Comment by LRAbbade** [comment]
Hello Yi,

Could you send me the steps you took to start the nodes? A screenshot of your terminal is good enough.

Kind regards,

Lucas Abbade

**Comment by qy201901** [comment]
Dear Lucas,
   Thank you very much for the prompt help. It's my mistake. When I use "node networkNode.js master full 192.168.0.1 this", everything is ok. Thank you very much for the contribution!

**Comment by qy201901** [comment]
Dear Lucas, 
    Could you kindly explain the purpose of this function:
    function isEndpointEnabled(req, res, callback){
      isBlockchainAvailabe ? callback() : res.json({note:" "})
     }              

Best wishes,
Yi

**Comment by LRAbbade** [comment]
> Dear Lucas,
> Could you kindly explain the purpose of this function:
> function isEndpointEnabled(req, res, callback){
> isBlockchainAvailabe ? callback() : res.json({note:" "})
> }
> 
> Best wishes,
> Yi

When you start a node, it must retrieve the Blockchain information from the network, in a real scenario where the Blockchain might be running for a long time, it might be millions of blocks long, which could make this process take a long time, while the blockchain is being retrieved, the node cannot actively participate in the network (ie voting), so if it receives any request, it will only respond that it is not available. Once the blockchain has been completely downloaded, it can become an active member of the network, thus the flag `isBlockchainAvailable` will be set to true, and requests will be answered as expected.

Since there’s no real issue, I will close this one, if you need further explanations, feel free to e-mail me: lucasabbade@hotmail.com

**Comment by qy201901** [comment]
Thank you very much!
